server:
  port: 8751
spring:
  application:
    name: service-miya
  zipkin:
    base-url: http://localhost:8741
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/