eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8711

spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-ribbon:
      path: /api-ribbon/**
      serviceId: service-ribbon
    api-hi:
      path: /api-hi/**
      serviceId: service-hi